version: '2.3'
services:
    rabbit-mq:
        image: rabbitmq:3-management
        ports:
            - "8010:15672"
            - "5671-5672:5671-5672"
        environment: 
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: public
            TZ: Asia/Bangkok
        restart: always
        container_name: rabbit-mq
        hostname: rabbit-mq
        networks:
            - ztrus_net
    inv-layout:
        image: thunchakorn/inv-layout:cpu
        container_name: inv-layout
        hostname: inv-layout
        restart: always
        volumes:
            - "./images/:/app/images"
            - "./weight/:/app/weight"
        environment:
            TZ: Asia/Bangkok
            RPC_HOST: amqp://user:public@rabbit-mq:5672/%2F?heartbeat=120
            RPC_KEY: inv-layout
            WEIGHT_PATH: ./weight/
        networks:
            - ztrus_net
        depends_on:
            - rabbit-mq
        command:
            python3 app.py

networks:
    ztrus_net: