version: '2.3'
services:
    rabbit:
        image: rabbitmq:3-management
        ports:
            - "8010:15672"
            - "5671-5672:5671-5672"
        environment: 
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: public
            TZ: Asia/Bangkok
        restart: always
        container_name: rabbit-mq
        hostname: rabbit-mq
        networks:
            - ztrus_net
    invoice-layout-detection:
        build:
            .
        container_name: invoice-layout-detection
        hostname: invoice-layout-detection
        restart: always
        runtime: nvidia
        volumes:
            - "./images/:/images"
        environment:
            TZ: Asia/Bangkok
            RPC_HOST: amqp://user:public@rabbit-mq:5672/%2F?heartbeat=120
            RPC_KEY: layout_detection
        networks:
            - ztrus_net
        depends_on:
            - rabbit
        command:
            python3 app.py
networks:
    ztrus_net: