version: '3'
services:
    client:
        image: wnuttachai/ubuntu18.04:base
        container_name: client
        ports:
            - "5000:80"
        volumes: 
            - "./:/app"
        command: 
            tail -F /dev/null
    rabbit:
        image: rabbitmq:3-management
        ports:
            - "8010:15672"
            - "5671-5672:5671-5672"
        environment: 
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: public
        restart: always
    server:
        build:
            ./server
        container_name: detectron2_predict_server
        ports:
            - "5001:80"
        volumes:
            - "./:/app"
        command: 
            tail -F /dev/null
